Repository mu-editor/mu, pull requests merged in 2021-01, with the labels that each got.

#1231 Add Seeedstudio XIAO to Circuit Python mode (#1206)
  mu/modes/circuitpython.py
Labels: mode: circuitpython

#1247 Readding `check` dependency to `macos` make target.
  .github/workflows/build.yml
  Makefile
Labels: packaging

#1250 Using pup to package under Windows
  .appveyor.yml
  .github/workflows/build.yml
  Makefile
  make.py
  package/mu_nsist.py
  setup.py
  win_installer.py
Labels: OS: Windows, packaging
