Repository mu-editor/mu, pull requests merged in 2022-02, with the labels that each got.

#1886 Add ru_RU translation
  mu/locale/ru_RU/LC_MESSAGES/mu.mo
  mu/locale/ru_RU/LC_MESSAGES/mu.po
Labels: i18n

#1385 Update japanese translate file.
  mu/locale/ja/LC_MESSAGES/mu.mo
  mu/locale/ja/LC_MESSAGES/mu.po
Labels: translations

#908 Add snek mode
  AUTHORS.rst
  mu/app.py
  mu/interface/main.py
  mu/interface/panes.py
  mu/modes/__init__.py
  mu/modes/api/__init__.py
  mu/modes/api/snek.py
  mu/modes/snek.py
  mu/resources/images/getflash.svg
  mu/resources/images/snek.svg
  tests/interface/test_main.py
  tests/interface/test_panes.py
  tests/modes/test_snek.py
  tests/virtual_environment/test_process.py
Labels: modes
